# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeSelection = QtWidgets.QTreeWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeSelection.sizePolicy().hasHeightForWidth())
        self.treeSelection.setSizePolicy(sizePolicy)
        self.treeSelection.setObjectName("treeSelection")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeSelection)
        item_0.setFlags(QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeSelection)
        item_0.setFlags(QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.horizontalLayout_5.addWidget(self.treeSelection)
        self.contentWidget_0 = QtWidgets.QWidget(self.widget)
        self.contentWidget_0.setObjectName("contentWidget_0")
        self.contentVerticalLayout_0 = QtWidgets.QVBoxLayout(self.contentWidget_0)
        self.contentVerticalLayout_0.setObjectName("contentVerticalLayout_0")
        self.textEdit_2 = QtWidgets.QTextEdit(self.contentWidget_0)
        self.textEdit_2.setObjectName("textEdit_2")
        self.contentVerticalLayout_0.addWidget(self.textEdit_2)
        self.horizontalLayout_5.addWidget(self.contentWidget_0)
        self.contentWidget_2 = QtWidgets.QWidget(self.widget)
        self.contentWidget_2.setObjectName("contentWidget_2")
        self.contentVerticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget_2)
        self.contentVerticalLayout_2.setObjectName("contentVerticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.contentWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.txtEditInitial = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtEditInitial.setPlainText("")
        self.txtEditInitial.setObjectName("txtEditInitial")
        self.gridLayout_8.addWidget(self.txtEditInitial, 0, 3, 1, 1)
        self.lblEpsilon_2 = QtWidgets.QLabel(self.groupBox_3)
        self.lblEpsilon_2.setObjectName("lblEpsilon_2")
        self.gridLayout_8.addWidget(self.lblEpsilon_2, 1, 2, 1, 1)
        self.txtEpsilon_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtEpsilon_2.setObjectName("txtEpsilon_2")
        self.gridLayout_8.addWidget(self.txtEpsilon_2, 1, 3, 1, 1)
        self.lblFunction_2 = QtWidgets.QLabel(self.groupBox_3)
        self.lblFunction_2.setObjectName("lblFunction_2")
        self.gridLayout_8.addWidget(self.lblFunction_2, 0, 0, 1, 1)
        self.txtMaxItr_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtMaxItr_2.setObjectName("txtMaxItr_2")
        self.gridLayout_8.addWidget(self.txtMaxItr_2, 1, 1, 1, 1)
        self.lblMaxItr_2 = QtWidgets.QLabel(self.groupBox_3)
        self.lblMaxItr_2.setObjectName("lblMaxItr_2")
        self.gridLayout_8.addWidget(self.lblMaxItr_2, 1, 0, 1, 1)
        self.txtEditEquations = QtWidgets.QPlainTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEditEquations.sizePolicy().hasHeightForWidth())
        self.txtEditEquations.setSizePolicy(sizePolicy)
        self.txtEditEquations.setPlainText("")
        self.txtEditEquations.setOverwriteMode(False)
        self.txtEditEquations.setPlaceholderText("")
        self.txtEditEquations.setObjectName("txtEditEquations")
        self.gridLayout_8.addWidget(self.txtEditEquations, 0, 1, 1, 1)
        self.contentVerticalLayout_2.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.contentVerticalLayout_2.addItem(spacerItem)
        self.btnResult_2 = QtWidgets.QPushButton(self.contentWidget_2)
        self.btnResult_2.setObjectName("btnResult_2")
        self.contentVerticalLayout_2.addWidget(self.btnResult_2)
        self.horizontalLayout_5.addWidget(self.contentWidget_2)
        self.contentWidget_1 = QtWidgets.QWidget(self.widget)
        self.contentWidget_1.setObjectName("contentWidget_1")
        self.contentVerticalLayout_1 = QtWidgets.QVBoxLayout(self.contentWidget_1)
        self.contentVerticalLayout_1.setObjectName("contentVerticalLayout_1")
        self.groupBox = QtWidgets.QGroupBox(self.contentWidget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtXl = QtWidgets.QLineEdit(self.groupBox)
        self.txtXl.setObjectName("txtXl")
        self.gridLayout_2.addWidget(self.txtXl, 2, 1, 1, 1)
        self.lblXu = QtWidgets.QLabel(self.groupBox)
        self.lblXu.setObjectName("lblXu")
        self.gridLayout_2.addWidget(self.lblXu, 2, 2, 1, 1)
        self.lblEpsilon = QtWidgets.QLabel(self.groupBox)
        self.lblEpsilon.setObjectName("lblEpsilon")
        self.gridLayout_2.addWidget(self.lblEpsilon, 3, 2, 1, 1)
        self.txtMaxItr = QtWidgets.QLineEdit(self.groupBox)
        self.txtMaxItr.setObjectName("txtMaxItr")
        self.gridLayout_2.addWidget(self.txtMaxItr, 3, 1, 1, 1)
        self.txtEpsilon = QtWidgets.QLineEdit(self.groupBox)
        self.txtEpsilon.setObjectName("txtEpsilon")
        self.gridLayout_2.addWidget(self.txtEpsilon, 3, 3, 1, 1)
        self.lblMaxItr = QtWidgets.QLabel(self.groupBox)
        self.lblMaxItr.setObjectName("lblMaxItr")
        self.gridLayout_2.addWidget(self.lblMaxItr, 3, 0, 1, 1)
        self.txtXu = QtWidgets.QLineEdit(self.groupBox)
        self.txtXu.setObjectName("txtXu")
        self.gridLayout_2.addWidget(self.txtXu, 2, 3, 1, 1)
        self.lblXl = QtWidgets.QLabel(self.groupBox)
        self.lblXl.setObjectName("lblXl")
        self.gridLayout_2.addWidget(self.lblXl, 2, 0, 1, 1)
        self.lblFunction = QtWidgets.QLabel(self.groupBox)
        self.lblFunction.setObjectName("lblFunction")
        self.gridLayout_2.addWidget(self.lblFunction, 0, 0, 1, 1)
        self.txtFunction = QtWidgets.QLineEdit(self.groupBox)
        self.txtFunction.setObjectName("txtFunction")
        self.gridLayout_2.addWidget(self.txtFunction, 0, 1, 1, 3)
        self.tabAllMethods = QtWidgets.QTabWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAllMethods.sizePolicy().hasHeightForWidth())
        self.tabAllMethods.setSizePolicy(sizePolicy)
        self.tabAllMethods.setObjectName("tabAllMethods")
        self.tabBisection = QtWidgets.QWidget()
        self.tabBisection.setObjectName("tabBisection")
        self.gridLayout = QtWidgets.QGridLayout(self.tabBisection)
        self.gridLayout.setObjectName("gridLayout")
        self.txtXlBisection = QtWidgets.QLineEdit(self.tabBisection)
        self.txtXlBisection.setObjectName("txtXlBisection")
        self.gridLayout.addWidget(self.txtXlBisection, 0, 1, 1, 1)
        self.lblXu2Bisection = QtWidgets.QLabel(self.tabBisection)
        self.lblXu2Bisection.setObjectName("lblXu2Bisection")
        self.gridLayout.addWidget(self.lblXu2Bisection, 0, 2, 1, 1)
        self.lblXlBisection = QtWidgets.QLabel(self.tabBisection)
        self.lblXlBisection.setObjectName("lblXlBisection")
        self.gridLayout.addWidget(self.lblXlBisection, 0, 0, 1, 1)
        self.txtXuBisection = QtWidgets.QLineEdit(self.tabBisection)
        self.txtXuBisection.setObjectName("txtXuBisection")
        self.gridLayout.addWidget(self.txtXuBisection, 0, 3, 1, 1)
        self.tabAllMethods.addTab(self.tabBisection, "")
        self.tabFalsePosition = QtWidgets.QWidget()
        self.tabFalsePosition.setObjectName("tabFalsePosition")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabFalsePosition)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblXlFalsePosition = QtWidgets.QLabel(self.tabFalsePosition)
        self.lblXlFalsePosition.setObjectName("lblXlFalsePosition")
        self.gridLayout_3.addWidget(self.lblXlFalsePosition, 0, 0, 1, 1)
        self.txtXlFalsePosition = QtWidgets.QLineEdit(self.tabFalsePosition)
        self.txtXlFalsePosition.setObjectName("txtXlFalsePosition")
        self.gridLayout_3.addWidget(self.txtXlFalsePosition, 0, 1, 1, 1)
        self.lblXuFalsePosition = QtWidgets.QLabel(self.tabFalsePosition)
        self.lblXuFalsePosition.setObjectName("lblXuFalsePosition")
        self.gridLayout_3.addWidget(self.lblXuFalsePosition, 0, 2, 1, 1)
        self.txtXuFalsePosition = QtWidgets.QLineEdit(self.tabFalsePosition)
        self.txtXuFalsePosition.setObjectName("txtXuFalsePosition")
        self.gridLayout_3.addWidget(self.txtXuFalsePosition, 0, 3, 1, 1)
        self.tabAllMethods.addTab(self.tabFalsePosition, "")
        self.tabFixedPoint = QtWidgets.QWidget()
        self.tabFixedPoint.setObjectName("tabFixedPoint")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabFixedPoint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblXiFixedPoint = QtWidgets.QLabel(self.tabFixedPoint)
        self.lblXiFixedPoint.setObjectName("lblXiFixedPoint")
        self.gridLayout_4.addWidget(self.lblXiFixedPoint, 0, 0, 1, 1)
        self.txtXiFixedPoint = QtWidgets.QLineEdit(self.tabFixedPoint)
        self.txtXiFixedPoint.setObjectName("txtXiFixedPoint")
        self.gridLayout_4.addWidget(self.txtXiFixedPoint, 0, 1, 1, 1)
        self.tabAllMethods.addTab(self.tabFixedPoint, "")
        self.tabNewtonRaphson = QtWidgets.QWidget()
        self.tabNewtonRaphson.setObjectName("tabNewtonRaphson")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabNewtonRaphson)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblXiNewtonRaphson = QtWidgets.QLabel(self.tabNewtonRaphson)
        self.lblXiNewtonRaphson.setObjectName("lblXiNewtonRaphson")
        self.gridLayout_6.addWidget(self.lblXiNewtonRaphson, 0, 0, 1, 1)
        self.txtXiNewtonRaphson = QtWidgets.QLineEdit(self.tabNewtonRaphson)
        self.txtXiNewtonRaphson.setObjectName("txtXiNewtonRaphson")
        self.gridLayout_6.addWidget(self.txtXiNewtonRaphson, 0, 1, 1, 1)
        self.tabAllMethods.addTab(self.tabNewtonRaphson, "")
        self.tabSecant = QtWidgets.QWidget()
        self.tabSecant.setObjectName("tabSecant")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabSecant)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtX2Secant = QtWidgets.QLineEdit(self.tabSecant)
        self.txtX2Secant.setObjectName("txtX2Secant")
        self.gridLayout_5.addWidget(self.txtX2Secant, 0, 3, 1, 1)
        self.lblX2Secant = QtWidgets.QLabel(self.tabSecant)
        self.lblX2Secant.setObjectName("lblX2Secant")
        self.gridLayout_5.addWidget(self.lblX2Secant, 0, 2, 1, 1)
        self.lblX1Secant = QtWidgets.QLabel(self.tabSecant)
        self.lblX1Secant.setObjectName("lblX1Secant")
        self.gridLayout_5.addWidget(self.lblX1Secant, 0, 0, 1, 1)
        self.txtX1Secant = QtWidgets.QLineEdit(self.tabSecant)
        self.txtX1Secant.setObjectName("txtX1Secant")
        self.gridLayout_5.addWidget(self.txtX1Secant, 0, 1, 1, 1)
        self.tabAllMethods.addTab(self.tabSecant, "")
        self.tabBiergeVieta = QtWidgets.QWidget()
        self.tabBiergeVieta.setObjectName("tabBiergeVieta")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabBiergeVieta)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblXiBiergeVieta = QtWidgets.QLabel(self.tabBiergeVieta)
        self.lblXiBiergeVieta.setObjectName("lblXiBiergeVieta")
        self.gridLayout_7.addWidget(self.lblXiBiergeVieta, 0, 0, 1, 1)
        self.txtXiBiergeVieta = QtWidgets.QLineEdit(self.tabBiergeVieta)
        self.txtXiBiergeVieta.setObjectName("txtXiBiergeVieta")
        self.gridLayout_7.addWidget(self.txtXiBiergeVieta, 0, 1, 1, 1)
        self.tabAllMethods.addTab(self.tabBiergeVieta, "")
        self.gridLayout_2.addWidget(self.tabAllMethods, 1, 0, 1, 4)
        self.contentVerticalLayout_1.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.contentVerticalLayout_1.addItem(spacerItem1)
        self.btnResult = QtWidgets.QPushButton(self.contentWidget_1)
        self.btnResult.setObjectName("btnResult")
        self.contentVerticalLayout_1.addWidget(self.btnResult)
        self.horizontalLayout_5.addWidget(self.contentWidget_1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resultTable = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTable.sizePolicy().hasHeightForWidth())
        self.resultTable.setSizePolicy(sizePolicy)
        self.resultTable.setMinimumSize(QtCore.QSize(0, 0))
        self.resultTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(4)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.resultTable)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnGaussSeidel = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGaussSeidel.setEnabled(False)
        self.btnGaussSeidel.setObjectName("btnGaussSeidel")
        self.horizontalLayout_4.addWidget(self.btnGaussSeidel)
        self.btnSingleStep = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSingleStep.setEnabled(False)
        self.btnSingleStep.setObjectName("btnSingleStep")
        self.horizontalLayout_4.addWidget(self.btnSingleStep)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAuto_Save = QtWidgets.QAction(MainWindow)
        self.actionAuto_Save.setCheckable(True)
        self.actionAuto_Save.setObjectName("actionAuto_Save")
        self.menuFile.addAction(self.actionAuto_Save)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabAllMethods.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeSelection.headerItem().setText(0, _translate("MainWindow", "Choose Method:"))
        __sortingEnabled = self.treeSelection.isSortingEnabled()
        self.treeSelection.setSortingEnabled(False)
        self.treeSelection.topLevelItem(0).setText(0, _translate("MainWindow", "Root Finder"))
        self.treeSelection.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Bisection"))
        self.treeSelection.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "False-Position"))
        self.treeSelection.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Fixed Point"))
        self.treeSelection.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Newton-Raphson"))
        self.treeSelection.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Secant"))
        self.treeSelection.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "Bierge-Vieta"))
        self.treeSelection.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "All Methods"))
        self.treeSelection.topLevelItem(1).setText(0, _translate("MainWindow", "System of Equations Solver"))
        self.treeSelection.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Gaussian-elimination"))
        self.treeSelection.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "LU decomposition"))
        self.treeSelection.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Gaussian-Jordan"))
        self.treeSelection.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Gauss-Seidel"))
        self.treeSelection.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "All"))
        self.treeSelection.setSortingEnabled(__sortingEnabled)
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Root Finder &amp; System of Linear Equations Solver</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">..</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">..</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Intro &amp; Features</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">..</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">. Styling sheets should make this field look better</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Inputs"))
        self.txtEditInitial.setPlaceholderText(_translate("MainWindow", "Initial Guesses"))
        self.lblEpsilon_2.setText(_translate("MainWindow", "Epsilon:"))
        self.txtEpsilon_2.setText(_translate("MainWindow", "0.00001"))
        self.lblFunction_2.setText(_translate("MainWindow", "Equations:"))
        self.txtMaxItr_2.setText(_translate("MainWindow", "50"))
        self.lblMaxItr_2.setText(_translate("MainWindow", "Max Iterations:"))
        self.txtEditEquations.setToolTip(_translate("MainWindow", "Enter each equation in a <b>seperate</b> line"))
        self.btnResult_2.setText(_translate("MainWindow", "Show Result"))
        self.groupBox.setTitle(_translate("MainWindow", "Inputs"))
        self.txtXl.setText(_translate("MainWindow", "0"))
        self.lblXu.setText(_translate("MainWindow", "Xu:"))
        self.lblEpsilon.setText(_translate("MainWindow", "Epsilon:"))
        self.txtMaxItr.setText(_translate("MainWindow", "50"))
        self.txtEpsilon.setText(_translate("MainWindow", "0.00001"))
        self.lblMaxItr.setText(_translate("MainWindow", "Max Iterations:"))
        self.txtXu.setText(_translate("MainWindow", "4"))
        self.lblXl.setText(_translate("MainWindow", "Xl:"))
        self.lblFunction.setText(_translate("MainWindow", "Function:"))
        self.txtFunction.setText(_translate("MainWindow", "x^2 - 9"))
        self.txtXlBisection.setText(_translate("MainWindow", "0"))
        self.lblXu2Bisection.setText(_translate("MainWindow", "Xu"))
        self.lblXlBisection.setText(_translate("MainWindow", "Xl:"))
        self.txtXuBisection.setText(_translate("MainWindow", "4"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabBisection), _translate("MainWindow", "Bisection"))
        self.lblXlFalsePosition.setText(_translate("MainWindow", "Xl:"))
        self.txtXlFalsePosition.setText(_translate("MainWindow", "0"))
        self.lblXuFalsePosition.setText(_translate("MainWindow", "Xu"))
        self.txtXuFalsePosition.setText(_translate("MainWindow", "4"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabFalsePosition), _translate("MainWindow", "False-Position"))
        self.lblXiFixedPoint.setText(_translate("MainWindow", "Xi:"))
        self.txtXiFixedPoint.setText(_translate("MainWindow", "4"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabFixedPoint), _translate("MainWindow", "Fixed Point"))
        self.lblXiNewtonRaphson.setText(_translate("MainWindow", "Xi:"))
        self.txtXiNewtonRaphson.setText(_translate("MainWindow", "4"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabNewtonRaphson), _translate("MainWindow", "Newton-Raphson"))
        self.txtX2Secant.setText(_translate("MainWindow", "4"))
        self.lblX2Secant.setText(_translate("MainWindow", "X2:"))
        self.lblX1Secant.setText(_translate("MainWindow", "X1:"))
        self.txtX1Secant.setText(_translate("MainWindow", "2"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabSecant), _translate("MainWindow", "Secant"))
        self.lblXiBiergeVieta.setText(_translate("MainWindow", "Xi:"))
        self.txtXiBiergeVieta.setText(_translate("MainWindow", "4"))
        self.tabAllMethods.setTabText(self.tabAllMethods.indexOf(self.tabBiergeVieta), _translate("MainWindow", "Bierge-Vieta"))
        self.btnResult.setText(_translate("MainWindow", "Show Result"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Number of Iterations"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Execution Time"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Approximate Root"))
        item = self.resultTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precision"))
        self.btnGaussSeidel.setText(_translate("MainWindow", "Details for Gauss-Siedel"))
        self.btnSingleStep.setText(_translate("MainWindow", "Single Step Mode"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAuto_Save.setText(_translate("MainWindow", "Auto Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

